/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment HeroSection on PageBuilderSectionsHeroLayout {\n    fieldGroupName\n    subHeading\n    heading\n    highlightedHeading\n    description\n    scheduleMeetingLabel\n    scheduleMeetingLink\n    tryDemoLabel\n    tryDemoLink\n    trophyIcon {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": typeof types.HeroSectionFragmentDoc,
    "\n  fragment CloudInnovatorsSection on PageBuilderSectionsCloudInnovatorsLayout {\n    fieldGroupName\n    headinSufix\n    headingPrefix\n    sectionHeading\n  }\n": typeof types.CloudInnovatorsSectionFragmentDoc,
    "\n  fragment TurningIdeasCloudPowerBusinessSection on PageBuilderSectionsTurningideascloudpowerbusinessLayout {\n    fieldGroupName\n    author\n    description1\n    description2\n    heading\n    stats {\n      fieldGroupName\n      description\n      prefix\n      suffix\n      value\n    }\n  }\n": typeof types.TurningIdeasCloudPowerBusinessSectionFragmentDoc,
    "\n  fragment CloudPowerBusinessSection on PageBuilderSectionsCloudPowerBusinessLayout {\n    fieldGroupName\n    description\n    heading\n    video {\n      fieldGroupName\n      imageovervideo {\n        node {\n          altText\n          link\n        }\n      }\n      overImage\n      videoUrl\n      videoPoster {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": typeof types.CloudPowerBusinessSectionFragmentDoc,
    "\n  fragment IntegratedCloudEcosystemSection on PageBuilderSectionsIntegratedCloudEcosystemLayout {\n    fieldGroupName\n    description\n    heading\n    platforms {\n      fieldGroupName\n      name\n      logo {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": typeof types.IntegratedCloudEcosystemSectionFragmentDoc,
    "\n  fragment StackConsoleFeaturesSection on PageBuilderSectionsStackConsoleFeaturesLayout {\n    fieldGroupName\n    description\n    heading\n    features {\n      fieldGroupName\n      name\n      featureDescription\n      featureButtonLabel\n      featureButtonLink\n      videoSection {\n        fieldGroupName\n        backgroundColor\n        video\n        videoCardTopBackgroundColor\n        videoPoster {\n          node {\n            altText\n            link\n          }\n        }\n      }\n    }\n  }\n": typeof types.StackConsoleFeaturesSectionFragmentDoc,
    "\n  fragment WhoIsForStackConsoleSection on PageBuilderSectionsWhoIsForStackConsoleLayout {\n    fieldGroupName\n    description\n    headign\n    tabs {\n      fieldGroupName\n      heading\n      description\n      learnMoreLabel\n      learnMoreLink\n      tabImage {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": typeof types.WhoIsForStackConsoleSectionFragmentDoc,
    "\n  fragment FaqsSection on PageBuilderSectionsFaqsLayout {\n    fieldGroupName\n    heading\n    questions {\n      fieldGroupName\n      question\n      answer\n    }\n  }\n": typeof types.FaqsSectionFragmentDoc,
    "\n  fragment BeforeFooterCtaSection on PageBuilderSectionsBeforefooterctaLayout {\n    fieldGroupName\n    heading\n    description\n    talkToTeamLabel\n    talkToTeamLink\n    tryALiveDemo\n  }\n": typeof types.BeforeFooterCtaSectionFragmentDoc,
    "\n  fragment CloudCommercePlatformSection on PageBuilderSectionsCloudCommercePlatformLayout {\n    fieldGroupName\n    heading\n    highlightedHeading\n    description\n    requestADemo\n    requestADemoLink\n    icon {\n      node {\n        altText\n        link\n      }\n    }\n    sectionImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": typeof types.CloudCommercePlatformSectionFragmentDoc,
    "\n  fragment InfiniteCloudConsoleSection on PageBuilderSectionsInfiniteCloudConsoleLayout {\n    fieldGroupName\n    heading\n    description\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": typeof types.InfiniteCloudConsoleSectionFragmentDoc,
    "\n  fragment PlatformCapabilitiesGridSection on PageBuilderSectionsPlatformCapabilitiesGridLayout {\n  fieldGroupName\n  heading\n  card1 { \n  cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card2 { \n    cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card3 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card4 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card5 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card6 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card7 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card8 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card9 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card10 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n}\n\n \n": typeof types.PlatformCapabilitiesGridSectionFragmentDoc,
    "\n  fragment ExperienceStackSection on PageBuilderSectionsExperienceStackLayout {\n    fieldGroupName\n  }\n": typeof types.ExperienceStackSectionFragmentDoc,
    "\n  fragment WhyChooseStackConsoleSection on PageBuilderSectionsWhyChooseStackConsoleLayout {\n    fieldGroupName\n  }\n": typeof types.WhyChooseStackConsoleSectionFragmentDoc,
    "\n  fragment CloudIntegrationsHeroSection on PageBuilderSectionsCloudIntegrationsHeroLayout {\n    fieldGroupName\n    heading\n    headingHighlighted\n    integrationButtonLabel\n    integrationButtonLink\n    backgroundImage {\n      node {\n        altText\n        link\n      }\n    }\n    backgroundImageMobile {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    brandLogos {\n      fieldGroupName\n        logo {\n          node {\n            altText\n            link\n            }\n        }\n      }\n  }\n": typeof types.CloudIntegrationsHeroSectionFragmentDoc,
    "\n  fragment CloudIntegrationsPostsSection on PageBuilderSectionsCloudIntegrationsPostsLayout {\n    fieldGroupName\n    heading\n    posts {\n      nodes {\n        ... on Post {\n          id\n          slug\n          title\n          excerpt\n          content\n          featuredImage {\n            node {\n              altText\n              link\n            }\n          }\n          categories {\n            nodes {\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.CloudIntegrationsPostsSectionFragmentDoc,
    "\n  fragment StackConsoleApisSection on PageBuilderSectionsStackConsoleApisLayout {\n      description\n      fieldGroupName\n      heading\n      headingHighlighted\n      sectionBackgroundImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImageMobile {\n        node {\n          altText\n          link\n        }\n      }\n  }\n": typeof types.StackConsoleApisSectionFragmentDoc,
    "\n  fragment CloudIntegrationsCTASection on PageBuilderSectionsCloudIntegrationsCtaLayout {\n    fieldGroupName\n    heading\n    description\n    actionButtonLabel\n    actionButtonLink\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": typeof types.CloudIntegrationsCtaSectionFragmentDoc,
    "\n  query PageSectionsByUri($uri: ID!) {\n    page(id: $uri, idType: URI) {\n      id\n      title\n      slug\n      uri\n      featuredImageId\n      link\n      pageBuilder {\n        sections {\n          __typename\n          fieldGroupName\n          ...HeroSection\n          ...CloudInnovatorsSection\n          ...TurningIdeasCloudPowerBusinessSection\n          ...CloudPowerBusinessSection\n          ...IntegratedCloudEcosystemSection\n          ...StackConsoleFeaturesSection\n          ...WhoIsForStackConsoleSection\n          ...FaqsSection\n          ...BeforeFooterCtaSection\n          ...CloudCommercePlatformSection\n          ...InfiniteCloudConsoleSection\n          ...PlatformCapabilitiesGridSection\n          ...ExperienceStackSection\n          ...WhyChooseStackConsoleSection\n          ...CloudIntegrationsHeroSection\n          ...CloudIntegrationsPostsSection\n          ...StackConsoleApisSection\n          ...CloudIntegrationsCTASection\n        }\n      }\n    }\n  }\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n": typeof types.PageSectionsByUriDocument,
};
const documents: Documents = {
    "\n  fragment HeroSection on PageBuilderSectionsHeroLayout {\n    fieldGroupName\n    subHeading\n    heading\n    highlightedHeading\n    description\n    scheduleMeetingLabel\n    scheduleMeetingLink\n    tryDemoLabel\n    tryDemoLink\n    trophyIcon {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": types.HeroSectionFragmentDoc,
    "\n  fragment CloudInnovatorsSection on PageBuilderSectionsCloudInnovatorsLayout {\n    fieldGroupName\n    headinSufix\n    headingPrefix\n    sectionHeading\n  }\n": types.CloudInnovatorsSectionFragmentDoc,
    "\n  fragment TurningIdeasCloudPowerBusinessSection on PageBuilderSectionsTurningideascloudpowerbusinessLayout {\n    fieldGroupName\n    author\n    description1\n    description2\n    heading\n    stats {\n      fieldGroupName\n      description\n      prefix\n      suffix\n      value\n    }\n  }\n": types.TurningIdeasCloudPowerBusinessSectionFragmentDoc,
    "\n  fragment CloudPowerBusinessSection on PageBuilderSectionsCloudPowerBusinessLayout {\n    fieldGroupName\n    description\n    heading\n    video {\n      fieldGroupName\n      imageovervideo {\n        node {\n          altText\n          link\n        }\n      }\n      overImage\n      videoUrl\n      videoPoster {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": types.CloudPowerBusinessSectionFragmentDoc,
    "\n  fragment IntegratedCloudEcosystemSection on PageBuilderSectionsIntegratedCloudEcosystemLayout {\n    fieldGroupName\n    description\n    heading\n    platforms {\n      fieldGroupName\n      name\n      logo {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": types.IntegratedCloudEcosystemSectionFragmentDoc,
    "\n  fragment StackConsoleFeaturesSection on PageBuilderSectionsStackConsoleFeaturesLayout {\n    fieldGroupName\n    description\n    heading\n    features {\n      fieldGroupName\n      name\n      featureDescription\n      featureButtonLabel\n      featureButtonLink\n      videoSection {\n        fieldGroupName\n        backgroundColor\n        video\n        videoCardTopBackgroundColor\n        videoPoster {\n          node {\n            altText\n            link\n          }\n        }\n      }\n    }\n  }\n": types.StackConsoleFeaturesSectionFragmentDoc,
    "\n  fragment WhoIsForStackConsoleSection on PageBuilderSectionsWhoIsForStackConsoleLayout {\n    fieldGroupName\n    description\n    headign\n    tabs {\n      fieldGroupName\n      heading\n      description\n      learnMoreLabel\n      learnMoreLink\n      tabImage {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n": types.WhoIsForStackConsoleSectionFragmentDoc,
    "\n  fragment FaqsSection on PageBuilderSectionsFaqsLayout {\n    fieldGroupName\n    heading\n    questions {\n      fieldGroupName\n      question\n      answer\n    }\n  }\n": types.FaqsSectionFragmentDoc,
    "\n  fragment BeforeFooterCtaSection on PageBuilderSectionsBeforefooterctaLayout {\n    fieldGroupName\n    heading\n    description\n    talkToTeamLabel\n    talkToTeamLink\n    tryALiveDemo\n  }\n": types.BeforeFooterCtaSectionFragmentDoc,
    "\n  fragment CloudCommercePlatformSection on PageBuilderSectionsCloudCommercePlatformLayout {\n    fieldGroupName\n    heading\n    highlightedHeading\n    description\n    requestADemo\n    requestADemoLink\n    icon {\n      node {\n        altText\n        link\n      }\n    }\n    sectionImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": types.CloudCommercePlatformSectionFragmentDoc,
    "\n  fragment InfiniteCloudConsoleSection on PageBuilderSectionsInfiniteCloudConsoleLayout {\n    fieldGroupName\n    heading\n    description\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": types.InfiniteCloudConsoleSectionFragmentDoc,
    "\n  fragment PlatformCapabilitiesGridSection on PageBuilderSectionsPlatformCapabilitiesGridLayout {\n  fieldGroupName\n  heading\n  card1 { \n  cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card2 { \n    cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card3 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card4 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card5 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card6 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card7 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card8 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card9 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card10 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n}\n\n \n": types.PlatformCapabilitiesGridSectionFragmentDoc,
    "\n  fragment ExperienceStackSection on PageBuilderSectionsExperienceStackLayout {\n    fieldGroupName\n  }\n": types.ExperienceStackSectionFragmentDoc,
    "\n  fragment WhyChooseStackConsoleSection on PageBuilderSectionsWhyChooseStackConsoleLayout {\n    fieldGroupName\n  }\n": types.WhyChooseStackConsoleSectionFragmentDoc,
    "\n  fragment CloudIntegrationsHeroSection on PageBuilderSectionsCloudIntegrationsHeroLayout {\n    fieldGroupName\n    heading\n    headingHighlighted\n    integrationButtonLabel\n    integrationButtonLink\n    backgroundImage {\n      node {\n        altText\n        link\n      }\n    }\n    backgroundImageMobile {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    brandLogos {\n      fieldGroupName\n        logo {\n          node {\n            altText\n            link\n            }\n        }\n      }\n  }\n": types.CloudIntegrationsHeroSectionFragmentDoc,
    "\n  fragment CloudIntegrationsPostsSection on PageBuilderSectionsCloudIntegrationsPostsLayout {\n    fieldGroupName\n    heading\n    posts {\n      nodes {\n        ... on Post {\n          id\n          slug\n          title\n          excerpt\n          content\n          featuredImage {\n            node {\n              altText\n              link\n            }\n          }\n          categories {\n            nodes {\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n": types.CloudIntegrationsPostsSectionFragmentDoc,
    "\n  fragment StackConsoleApisSection on PageBuilderSectionsStackConsoleApisLayout {\n      description\n      fieldGroupName\n      heading\n      headingHighlighted\n      sectionBackgroundImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImageMobile {\n        node {\n          altText\n          link\n        }\n      }\n  }\n": types.StackConsoleApisSectionFragmentDoc,
    "\n  fragment CloudIntegrationsCTASection on PageBuilderSectionsCloudIntegrationsCtaLayout {\n    fieldGroupName\n    heading\n    description\n    actionButtonLabel\n    actionButtonLink\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n": types.CloudIntegrationsCtaSectionFragmentDoc,
    "\n  query PageSectionsByUri($uri: ID!) {\n    page(id: $uri, idType: URI) {\n      id\n      title\n      slug\n      uri\n      featuredImageId\n      link\n      pageBuilder {\n        sections {\n          __typename\n          fieldGroupName\n          ...HeroSection\n          ...CloudInnovatorsSection\n          ...TurningIdeasCloudPowerBusinessSection\n          ...CloudPowerBusinessSection\n          ...IntegratedCloudEcosystemSection\n          ...StackConsoleFeaturesSection\n          ...WhoIsForStackConsoleSection\n          ...FaqsSection\n          ...BeforeFooterCtaSection\n          ...CloudCommercePlatformSection\n          ...InfiniteCloudConsoleSection\n          ...PlatformCapabilitiesGridSection\n          ...ExperienceStackSection\n          ...WhyChooseStackConsoleSection\n          ...CloudIntegrationsHeroSection\n          ...CloudIntegrationsPostsSection\n          ...StackConsoleApisSection\n          ...CloudIntegrationsCTASection\n        }\n      }\n    }\n  }\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n": types.PageSectionsByUriDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment HeroSection on PageBuilderSectionsHeroLayout {\n    fieldGroupName\n    subHeading\n    heading\n    highlightedHeading\n    description\n    scheduleMeetingLabel\n    scheduleMeetingLink\n    tryDemoLabel\n    tryDemoLink\n    trophyIcon {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment HeroSection on PageBuilderSectionsHeroLayout {\n    fieldGroupName\n    subHeading\n    heading\n    highlightedHeading\n    description\n    scheduleMeetingLabel\n    scheduleMeetingLink\n    tryDemoLabel\n    tryDemoLink\n    trophyIcon {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudInnovatorsSection on PageBuilderSectionsCloudInnovatorsLayout {\n    fieldGroupName\n    headinSufix\n    headingPrefix\n    sectionHeading\n  }\n"): (typeof documents)["\n  fragment CloudInnovatorsSection on PageBuilderSectionsCloudInnovatorsLayout {\n    fieldGroupName\n    headinSufix\n    headingPrefix\n    sectionHeading\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment TurningIdeasCloudPowerBusinessSection on PageBuilderSectionsTurningideascloudpowerbusinessLayout {\n    fieldGroupName\n    author\n    description1\n    description2\n    heading\n    stats {\n      fieldGroupName\n      description\n      prefix\n      suffix\n      value\n    }\n  }\n"): (typeof documents)["\n  fragment TurningIdeasCloudPowerBusinessSection on PageBuilderSectionsTurningideascloudpowerbusinessLayout {\n    fieldGroupName\n    author\n    description1\n    description2\n    heading\n    stats {\n      fieldGroupName\n      description\n      prefix\n      suffix\n      value\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudPowerBusinessSection on PageBuilderSectionsCloudPowerBusinessLayout {\n    fieldGroupName\n    description\n    heading\n    video {\n      fieldGroupName\n      imageovervideo {\n        node {\n          altText\n          link\n        }\n      }\n      overImage\n      videoUrl\n      videoPoster {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CloudPowerBusinessSection on PageBuilderSectionsCloudPowerBusinessLayout {\n    fieldGroupName\n    description\n    heading\n    video {\n      fieldGroupName\n      imageovervideo {\n        node {\n          altText\n          link\n        }\n      }\n      overImage\n      videoUrl\n      videoPoster {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment IntegratedCloudEcosystemSection on PageBuilderSectionsIntegratedCloudEcosystemLayout {\n    fieldGroupName\n    description\n    heading\n    platforms {\n      fieldGroupName\n      name\n      logo {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment IntegratedCloudEcosystemSection on PageBuilderSectionsIntegratedCloudEcosystemLayout {\n    fieldGroupName\n    description\n    heading\n    platforms {\n      fieldGroupName\n      name\n      logo {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment StackConsoleFeaturesSection on PageBuilderSectionsStackConsoleFeaturesLayout {\n    fieldGroupName\n    description\n    heading\n    features {\n      fieldGroupName\n      name\n      featureDescription\n      featureButtonLabel\n      featureButtonLink\n      videoSection {\n        fieldGroupName\n        backgroundColor\n        video\n        videoCardTopBackgroundColor\n        videoPoster {\n          node {\n            altText\n            link\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment StackConsoleFeaturesSection on PageBuilderSectionsStackConsoleFeaturesLayout {\n    fieldGroupName\n    description\n    heading\n    features {\n      fieldGroupName\n      name\n      featureDescription\n      featureButtonLabel\n      featureButtonLink\n      videoSection {\n        fieldGroupName\n        backgroundColor\n        video\n        videoCardTopBackgroundColor\n        videoPoster {\n          node {\n            altText\n            link\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment WhoIsForStackConsoleSection on PageBuilderSectionsWhoIsForStackConsoleLayout {\n    fieldGroupName\n    description\n    headign\n    tabs {\n      fieldGroupName\n      heading\n      description\n      learnMoreLabel\n      learnMoreLink\n      tabImage {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment WhoIsForStackConsoleSection on PageBuilderSectionsWhoIsForStackConsoleLayout {\n    fieldGroupName\n    description\n    headign\n    tabs {\n      fieldGroupName\n      heading\n      description\n      learnMoreLabel\n      learnMoreLink\n      tabImage {\n        node {\n          altText\n          link\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment FaqsSection on PageBuilderSectionsFaqsLayout {\n    fieldGroupName\n    heading\n    questions {\n      fieldGroupName\n      question\n      answer\n    }\n  }\n"): (typeof documents)["\n  fragment FaqsSection on PageBuilderSectionsFaqsLayout {\n    fieldGroupName\n    heading\n    questions {\n      fieldGroupName\n      question\n      answer\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BeforeFooterCtaSection on PageBuilderSectionsBeforefooterctaLayout {\n    fieldGroupName\n    heading\n    description\n    talkToTeamLabel\n    talkToTeamLink\n    tryALiveDemo\n  }\n"): (typeof documents)["\n  fragment BeforeFooterCtaSection on PageBuilderSectionsBeforefooterctaLayout {\n    fieldGroupName\n    heading\n    description\n    talkToTeamLabel\n    talkToTeamLink\n    tryALiveDemo\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudCommercePlatformSection on PageBuilderSectionsCloudCommercePlatformLayout {\n    fieldGroupName\n    heading\n    highlightedHeading\n    description\n    requestADemo\n    requestADemoLink\n    icon {\n      node {\n        altText\n        link\n      }\n    }\n    sectionImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CloudCommercePlatformSection on PageBuilderSectionsCloudCommercePlatformLayout {\n    fieldGroupName\n    heading\n    highlightedHeading\n    description\n    requestADemo\n    requestADemoLink\n    icon {\n      node {\n        altText\n        link\n      }\n    }\n    sectionImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment InfiniteCloudConsoleSection on PageBuilderSectionsInfiniteCloudConsoleLayout {\n    fieldGroupName\n    heading\n    description\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment InfiniteCloudConsoleSection on PageBuilderSectionsInfiniteCloudConsoleLayout {\n    fieldGroupName\n    heading\n    description\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment PlatformCapabilitiesGridSection on PageBuilderSectionsPlatformCapabilitiesGridLayout {\n  fieldGroupName\n  heading\n  card1 { \n  cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card2 { \n    cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card3 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card4 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card5 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card6 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card7 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card8 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card9 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card10 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n}\n\n \n"): (typeof documents)["\n  fragment PlatformCapabilitiesGridSection on PageBuilderSectionsPlatformCapabilitiesGridLayout {\n  fieldGroupName\n  heading\n  card1 { \n  cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card2 { \n    cardImage {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    heading \n  }\n  card3 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card4 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card5 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card6 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card7 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card8 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card9 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n  card10 { cardImage {\n    node {\n      altText\n      link\n    }\n  }\n  description\n  heading }\n}\n\n \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment ExperienceStackSection on PageBuilderSectionsExperienceStackLayout {\n    fieldGroupName\n  }\n"): (typeof documents)["\n  fragment ExperienceStackSection on PageBuilderSectionsExperienceStackLayout {\n    fieldGroupName\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment WhyChooseStackConsoleSection on PageBuilderSectionsWhyChooseStackConsoleLayout {\n    fieldGroupName\n  }\n"): (typeof documents)["\n  fragment WhyChooseStackConsoleSection on PageBuilderSectionsWhyChooseStackConsoleLayout {\n    fieldGroupName\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudIntegrationsHeroSection on PageBuilderSectionsCloudIntegrationsHeroLayout {\n    fieldGroupName\n    heading\n    headingHighlighted\n    integrationButtonLabel\n    integrationButtonLink\n    backgroundImage {\n      node {\n        altText\n        link\n      }\n    }\n    backgroundImageMobile {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    brandLogos {\n      fieldGroupName\n        logo {\n          node {\n            altText\n            link\n            }\n        }\n      }\n  }\n"): (typeof documents)["\n  fragment CloudIntegrationsHeroSection on PageBuilderSectionsCloudIntegrationsHeroLayout {\n    fieldGroupName\n    heading\n    headingHighlighted\n    integrationButtonLabel\n    integrationButtonLink\n    backgroundImage {\n      node {\n        altText\n        link\n      }\n    }\n    backgroundImageMobile {\n      node {\n        altText\n        link\n      }\n    }\n    description\n    brandLogos {\n      fieldGroupName\n        logo {\n          node {\n            altText\n            link\n            }\n        }\n      }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudIntegrationsPostsSection on PageBuilderSectionsCloudIntegrationsPostsLayout {\n    fieldGroupName\n    heading\n    posts {\n      nodes {\n        ... on Post {\n          id\n          slug\n          title\n          excerpt\n          content\n          featuredImage {\n            node {\n              altText\n              link\n            }\n          }\n          categories {\n            nodes {\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CloudIntegrationsPostsSection on PageBuilderSectionsCloudIntegrationsPostsLayout {\n    fieldGroupName\n    heading\n    posts {\n      nodes {\n        ... on Post {\n          id\n          slug\n          title\n          excerpt\n          content\n          featuredImage {\n            node {\n              altText\n              link\n            }\n          }\n          categories {\n            nodes {\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment StackConsoleApisSection on PageBuilderSectionsStackConsoleApisLayout {\n      description\n      fieldGroupName\n      heading\n      headingHighlighted\n      sectionBackgroundImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImageMobile {\n        node {\n          altText\n          link\n        }\n      }\n  }\n"): (typeof documents)["\n  fragment StackConsoleApisSection on PageBuilderSectionsStackConsoleApisLayout {\n      description\n      fieldGroupName\n      heading\n      headingHighlighted\n      sectionBackgroundImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImage {\n        node {\n          altText\n          link\n        }\n      }\n      sectionMainImageMobile {\n        node {\n          altText\n          link\n        }\n      }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CloudIntegrationsCTASection on PageBuilderSectionsCloudIntegrationsCtaLayout {\n    fieldGroupName\n    heading\n    description\n    actionButtonLabel\n    actionButtonLink\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CloudIntegrationsCTASection on PageBuilderSectionsCloudIntegrationsCtaLayout {\n    fieldGroupName\n    heading\n    description\n    actionButtonLabel\n    actionButtonLink\n    heroImage {\n      node {\n        altText\n        link\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query PageSectionsByUri($uri: ID!) {\n    page(id: $uri, idType: URI) {\n      id\n      title\n      slug\n      uri\n      featuredImageId\n      link\n      pageBuilder {\n        sections {\n          __typename\n          fieldGroupName\n          ...HeroSection\n          ...CloudInnovatorsSection\n          ...TurningIdeasCloudPowerBusinessSection\n          ...CloudPowerBusinessSection\n          ...IntegratedCloudEcosystemSection\n          ...StackConsoleFeaturesSection\n          ...WhoIsForStackConsoleSection\n          ...FaqsSection\n          ...BeforeFooterCtaSection\n          ...CloudCommercePlatformSection\n          ...InfiniteCloudConsoleSection\n          ...PlatformCapabilitiesGridSection\n          ...ExperienceStackSection\n          ...WhyChooseStackConsoleSection\n          ...CloudIntegrationsHeroSection\n          ...CloudIntegrationsPostsSection\n          ...StackConsoleApisSection\n          ...CloudIntegrationsCTASection\n        }\n      }\n    }\n  }\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n"): (typeof documents)["\n  query PageSectionsByUri($uri: ID!) {\n    page(id: $uri, idType: URI) {\n      id\n      title\n      slug\n      uri\n      featuredImageId\n      link\n      pageBuilder {\n        sections {\n          __typename\n          fieldGroupName\n          ...HeroSection\n          ...CloudInnovatorsSection\n          ...TurningIdeasCloudPowerBusinessSection\n          ...CloudPowerBusinessSection\n          ...IntegratedCloudEcosystemSection\n          ...StackConsoleFeaturesSection\n          ...WhoIsForStackConsoleSection\n          ...FaqsSection\n          ...BeforeFooterCtaSection\n          ...CloudCommercePlatformSection\n          ...InfiniteCloudConsoleSection\n          ...PlatformCapabilitiesGridSection\n          ...ExperienceStackSection\n          ...WhyChooseStackConsoleSection\n          ...CloudIntegrationsHeroSection\n          ...CloudIntegrationsPostsSection\n          ...StackConsoleApisSection\n          ...CloudIntegrationsCTASection\n        }\n      }\n    }\n  }\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;